<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="7" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Cmas_360_Agent" duration-ms="177860" started-at="2020-11-09T11:16:56Z" finished-at="2020-11-09T11:19:53Z">
    <groups>
    </groups>
    <test name="ValidInputsToCreateNewCompany" duration-ms="32374" started-at="2020-11-09T11:16:56Z" finished-at="2020-11-09T11:17:28Z">
      <class name="testCases.TC_001">
        <test-method status="PASS" signature="login()[pri:0, instance:testCases.TC_001@59f99ea]" name="login" duration-ms="32344" started-at="2020-11-09T11:16:56Z" finished-at="2020-11-09T11:17:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testCases.TC_001@59f99ea]" name="teardown" is-config="true" duration-ms="16" started-at="2020-11-09T11:17:28Z" finished-at="2020-11-09T11:17:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=SUCCESS method=TC_001.login()[pri:0, instance:testCases.TC_001@59f99ea] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC_001 -->
    </test> <!-- ValidInputsToCreateNewCompany -->
    <test name="InvalidInputsToCreateNewCompany" duration-ms="14788" started-at="2020-11-09T11:17:28Z" finished-at="2020-11-09T11:17:43Z">
      <class name="testCases.TC_002">
        <test-method status="FAIL" signature="failedtest()[pri:0, instance:testCases.TC_002@13deb50e]" name="failedtest" duration-ms="13502" started-at="2020-11-09T11:17:28Z" finished-at="2020-11-09T11:17:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [nd soft] but found [Rnd soft]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [nd soft] but found [Rnd soft]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testCases.TC_002.failedtest(TC_002.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedtest -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testCases.TC_002@13deb50e]" name="teardown" is-config="true" duration-ms="1285" started-at="2020-11-09T11:17:41Z" finished-at="2020-11-09T11:17:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=failedtest status=FAILURE method=TC_002.failedtest()[pri:0, instance:testCases.TC_002@13deb50e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC_002 -->
    </test> <!-- InvalidInputsToCreateNewCompany -->
    <test name="GivenValidInputsToCancel" duration-ms="14343" started-at="2020-11-09T11:17:43Z" finished-at="2020-11-09T11:17:57Z">
      <class name="testCases.TC_003">
        <test-method status="PASS" signature="ValidCancel()[pri:0, instance:testCases.TC_003@5f341870]" name="ValidCancel" duration-ms="14343" started-at="2020-11-09T11:17:43Z" finished-at="2020-11-09T11:17:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidCancel -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testCases.TC_003@5f341870]" name="teardown" is-config="true" duration-ms="0" started-at="2020-11-09T11:17:57Z" finished-at="2020-11-09T11:17:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidCancel status=SUCCESS method=TC_003.ValidCancel()[pri:0, instance:testCases.TC_003@5f341870] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC_003 -->
    </test> <!-- GivenValidInputsToCancel -->
    <test name="GivenInvalidInputsToCancel" duration-ms="15469" started-at="2020-11-09T11:17:57Z" finished-at="2020-11-09T11:18:13Z">
      <class name="testCases.TC_004">
        <test-method status="PASS" signature="InvalidCancel()[pri:0, instance:testCases.TC_004@59ec2012]" name="InvalidCancel" duration-ms="15453" started-at="2020-11-09T11:17:57Z" finished-at="2020-11-09T11:18:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidCancel -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testCases.TC_004@59ec2012]" name="teardown" is-config="true" duration-ms="16" started-at="2020-11-09T11:18:13Z" finished-at="2020-11-09T11:18:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=InvalidCancel status=SUCCESS method=TC_004.InvalidCancel()[pri:0, instance:testCases.TC_004@59ec2012] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC_004 -->
    </test> <!-- GivenInvalidInputsToCancel -->
    <test name="EmptyValidationToSave" duration-ms="41465" started-at="2020-11-09T11:18:13Z" finished-at="2020-11-09T11:18:54Z">
      <class name="testCases.TC_005">
        <test-method status="FAIL" signature="EmptyValidationToSave()[pri:0, instance:testCases.TC_005@6fd02e5]" name="EmptyValidationToSave" duration-ms="40254" started-at="2020-11-09T11:18:13Z" finished-at="2020-11-09T11:18:53Z">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[7]/div[7]/div/button"}
  (Session info: chrome=86.0.4240.183)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'CP1059', ip: '192.168.43.116', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 86.0.4240.183, chrome: {chromedriverVersion: 85.0.4183.87 (cd6713ebf92fa..., userDataDir: C:\Users\RNDSOF~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:57074}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: d08b2a8e84662116a917e1d0409f4c2f
*** Element info: {Using=xpath, value=/html/body/div[7]/div[7]/div/button}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[7]/div[7]/div/button"}
  (Session info: chrome=86.0.4240.183)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'CP1059', ip: '192.168.43.116', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 86.0.4240.183, chrome: {chromedriverVersion: 85.0.4183.87 (cd6713ebf92fa..., userDataDir: C:\Users\RNDSOF~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:57074}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: d08b2a8e84662116a917e1d0409f4c2f
*** Element info: {Using=xpath, value=/html/body/div[7]/div[7]/div/button}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at com.sun.proxy.$Proxy10.click(Unknown Source)
at testCases.TC_005.EmptyValidationToSave(TC_005.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmptyValidationToSave -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testCases.TC_005@6fd02e5]" name="teardown" is-config="true" duration-ms="1201" started-at="2020-11-09T11:18:53Z" finished-at="2020-11-09T11:18:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=EmptyValidationToSave status=FAILURE method=TC_005.EmptyValidationToSave()[pri:0, instance:testCases.TC_005@6fd02e5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC_005 -->
    </test> <!-- EmptyValidationToSave -->
    <test name="illegelValidationToSave" duration-ms="13834" started-at="2020-11-09T11:18:54Z" finished-at="2020-11-09T11:19:08Z">
      <class name="testCases.TC_006">
        <test-method status="PASS" signature="illegelValidationToSave()[pri:0, instance:testCases.TC_006@56ac3a89]" name="illegelValidationToSave" duration-ms="13819" started-at="2020-11-09T11:18:54Z" finished-at="2020-11-09T11:19:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- illegelValidationToSave -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testCases.TC_006@56ac3a89]" name="teardown" is-config="true" duration-ms="0" started-at="2020-11-09T11:19:08Z" finished-at="2020-11-09T11:19:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=illegelValidationToSave status=SUCCESS method=TC_006.illegelValidationToSave()[pri:0, instance:testCases.TC_006@56ac3a89] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC_006 -->
    </test> <!-- illegelValidationToSave -->
    <test name="emptyValidationToCancel" duration-ms="45503" started-at="2020-11-09T11:19:08Z" finished-at="2020-11-09T11:19:53Z">
      <class name="testCases.TC_007">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testCases.TC_007@13805618]" name="launchBrowser" is-config="true" duration-ms="9939" started-at="2020-11-09T11:16:46Z" finished-at="2020-11-09T11:16:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="emptyValidationToCancel()[pri:0, instance:testCases.TC_007@13805618]" name="emptyValidationToCancel" duration-ms="44033" started-at="2020-11-09T11:19:08Z" finished-at="2020-11-09T11:19:52Z">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='tblcompany']/tbody/tr[*]/td[text()='']"}
  (Session info: chrome=86.0.4240.183)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'CP1059', ip: '192.168.43.116', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 86.0.4240.183, chrome: {chromedriverVersion: 85.0.4183.87 (cd6713ebf92fa..., userDataDir: C:\Users\RNDSOF~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:57074}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: d08b2a8e84662116a917e1d0409f4c2f
*** Element info: {Using=xpath, value=//*[@id='tblcompany']/tbody/tr[*]/td[text()='']}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='tblcompany']/tbody/tr[*]/td[text()='']"}
  (Session info: chrome=86.0.4240.183)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'CP1059', ip: '192.168.43.116', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 86.0.4240.183, chrome: {chromedriverVersion: 85.0.4183.87 (cd6713ebf92fa..., userDataDir: C:\Users\RNDSOF~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:57074}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: d08b2a8e84662116a917e1d0409f4c2f
*** Element info: {Using=xpath, value=//*[@id='tblcompany']/tbody/tr[*]/td[text()='']}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at testCases.TC_007.emptyValidationToCancel(TC_007.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyValidationToCancel -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testCases.TC_007@13805618]" name="teardown" is-config="true" duration-ms="1454" started-at="2020-11-09T11:19:52Z" finished-at="2020-11-09T11:19:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=emptyValidationToCancel status=FAILURE method=TC_007.emptyValidationToCancel()[pri:0, instance:testCases.TC_007@13805618] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="close()[pri:0, instance:testCases.TC_007@13805618]" name="close" is-config="true" duration-ms="228" started-at="2020-11-09T11:19:53Z" finished-at="2020-11-09T11:19:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- testCases.TC_007 -->
    </test> <!-- emptyValidationToCancel -->
  </suite> <!-- Cmas_360_Agent -->
</testng-results>
